### ISSUE TITLE
Web Build Issue

### ISSUE THREAD

**Issue by cemalgnlts** [godotjs/GodotJS#38]
Hi,
I get this error when compiling for web:

```sh
compiling modules/GodotJS/internal/jsb_process.cpp ...
In file included from modules/GodotJS/register_types.cpp:4:
modules/GodotJS/weaver/jsb_script.h:128:27: error: virtual function 'get_rpc_config' has a different return type ('const Variant') than the function it overrides (which has return type 'Variant')
  128 |     virtual const Variant get_rpc_config() const override;
      |                   ~~~~~~~ ^
./core/object/script_language.h:188:18: note: overridden virtual function is here
  188 |         virtual Variant get_rpc_config() const = 0;
      |                 ~~~~~~~ ^
1 error generated.
scons: *** [modules/GodotJS/register_types.web.template_release.wasm32.o] Error 1
scons: building terminated because of errors.
```

**Comment by ialex32x** [comment]
It's a godot version compatibility issue, which version you use?

**Comment by cemalgnlts** [comment]
Latest version.

**Comment by cemalgnlts** [comment]
Thank, It worked on version 4.2

**Comment by ialex32x** [comment]
The compiler errors are fixed on godot 4.4 now.

**Comment by cemalgnlts** [comment]
Great, thanks.
